### ISSUE TITLE
kubeversion compare issue

### ISSUE THREAD

**Issue by emouawad** [fmjstudios/helm#11]
### Name and Version

vaultwarden 0.2.1

### What architecture are you using?

None

### What steps will reproduce the bug?

Clean new installation

### Are you using any custom parameters or values?

```cmd
helm install --namespace vaultwarden --create-namespace `
--repo https://fmjstudios.github.io/helm/ `
--values values.yml `
vaultwarden vaultwarden --debug
```

### What is the expected behavior?

Installation successful 

### What do you see instead?

Error: INSTALLATION FAILED: chart requires kubeVersion: >=1.26 which is incompatible with Kubernetes v1.29.6-gke.1254000
helm.go:84: [debug] chart requires kubeVersion: >=1.26 which is incompatible with Kubernetes v1.29.6-gke.1254000

### Additional information

kubeversion v1.29 is more recent than 1.26 - should be accepted to install

**Comment by emouawad** [comment]
Nothing special about the way i am installing it. I  downloaded ur chart and installed it from folder getting same error. Only when i removed the kubeVersion attribute it succeeded.

It's definitely the format of that value - i suspect it should be another format.
Currently i am not on my dev machine but using the same command i installed 60+ chart such as prometheus-stack, bitnami charts etc

**Comment by FMJdev** [comment]
Hey @emouawad, thanks for the information! I double checked with the charts you mentioned and they indeed use a different format like `>=1.21.0-0` to define the `kubeVersion`. This seems to enable the snapshot-like versioning used for GKE clusters in addition to the normal SemVer definition.

I will issue a patch version update for all charts in the coming hours where I update the `kubeVersion` to the format mentioned above. Would you mind testing if the installation works then?

**Comment by emouawad** [comment]
Sure! thanks for the fast response ❤️

**Comment by FMJdev** [comment]
Hey @emouawad, I just published those patch versions for all charts alongside our new `keycloak-operator` chart. I'll be waiting for your feedback, if that fixed the issue 🙌🏼

**Comment by emouawad** [comment]
Yes, that fixes it - thanks

**Comment by FMJdev** [comment]
Thank you for your input! 😄 I was even looking up how to integrate GKE, AKS, EKS compatibility into my CI not too long ago. Needless to say your input was crucial in improving my charts' compatibility 🙌🏼
